### ISSUE TITLE
Decal projector is not enlisted on shader list..

### ISSUE THREAD

**Issue by Hastenswift** [naelstrof/SkinnedMeshDecals#10]
![isue](https://user-images.githubusercontent.com/34318106/161222668-e75e9a82-d4ca-403b-a937-8f7f05319f90.png)

How to make it work in standard render pipeline version 2019.4? the shaders under Naelstrof name dont show in standard RP when i set a shader from drop down list, but everything works in HDRP, i cant choose hdrp cuz its android . what to do, or what are exactly the Decal Projector shaders? are they with _DecalColorMap too..?     This Asset is best possible on internet about decaling skinmeshes, good job.

Also for people that get UV seams texel bleeds, after enabling Generating UV lightmaps, try set higher to the max, the Angle and Area Error factor.

**Comment by naelstrof** [comment]
That's strange, it shouldn't matter which pipeline you're on. If you could select the shader in the project tab and look at it in the inspector for errors. That would help tremendously. I only tested things on the 2020 LTS.

**Comment by Hastenswift** [comment]
![isue](https://user-images.githubusercontent.com/34318106/161228218-4f05a309-20b9-4096-bf19-75555429fb5b.png)

**Comment by naelstrof** [comment]
That screenshot accidentally cut off the line number. Mind showing which line that error is on?

**Comment by Hastenswift** [comment]
same error on DecalProjector, DecalProjectorsubtractive, SPhere Projector and sphereProjectorSubtractive

**Comment by Hastenswift** [comment]
Line 36 for Decal Projectors, other errors are 35 37 on others shaders

**Comment by naelstrof** [comment]
Found out this is due to the ConservativeRendering flag, which isn't supported on old versions of Unity.

When I get around to refactoring the project, I'll address this.

**Comment by naelstrof** [comment]
This should be addressed as of [v6.7.5](https://github.com/naelstrof/SkinnedMeshDecals/tree/v6.7.5). I use a different method for dilation now that takes a bit more memory.
