### ISSUE TITLE
Not working with human model.

### ISSUE THREAD

**Issue by manking99** [naelstrof/SkinnedMeshDecals#12]
Hi! 
According to the instructions, I changed the settings for the material in the human model. But coloring is only a robot model. If a human material is stretched on the robot model (with the correct shader), then the same is colored. 
But a man with both his texture and the texture of a robot does not get colored at all. 
It turns out that the models need to be edited somehow already in the blender? Or is any humanoid model from the asset store suitable for coloring? Project HDRP.

![Screenshot at Nov 30 03-05-25](https://user-images.githubusercontent.com/5559817/204676159-f5f6fd09-82a4-46c8-957a-9d31ffd47f3a.png)

![Screenshot at Nov 30 03-17-50](https://user-images.githubusercontent.com/5559817/204676892-1c01fa0e-61cd-476f-b711-c6ed0f83276c.png)

![Screenshot at Nov 30 03-17-28](https://user-images.githubusercontent.com/5559817/204676905-270168cc-aa3c-4e7d-86af-0d5c17f0694c.png)

**Comment by naelstrof** [comment]
Thank you for the very informative post, almost everything is set up correctly.

In my test scene, I use colliders to detect with a mesh is hit. If you wanted the human model to be colored by the test scene, you would need to add identical colliders so that the raycasts can detect it.

Alternatively you'll need to create your own script that calls decal code on your target mesh.

Let me know if that helps!

**Comment by manking99** [comment]
I tried adding colliders everywhere and checked the layers. The hit event is triggered. 
I used a large box collider on robots and humans. Colliders work for everyone.

![image](https://user-images.githubusercontent.com/5559817/204740385-c541fe75-9a10-413d-8a76-a59abeb65e02.png)
![image](https://user-images.githubusercontent.com/5559817/204740503-78be81f0-b5de-45f7-951d-23fc2b78fef1.png)
![image](https://user-images.githubusercontent.com/5559817/204740597-339f2189-2652-4918-930d-9fe19466d345.png)
![image](https://user-images.githubusercontent.com/5559817/204741024-351f22f1-10dc-4c8e-a451-53fe02a86b0c.png)

![image](https://user-images.githubusercontent.com/5559817/204740892-20201316-e003-4098-8328-3d008567f5a0.png)

**Comment by manking99** [comment]
And that's it. Figured it out. 
The character where the animator object was not connected LOD.

![image](https://user-images.githubusercontent.com/5559817/204759829-52e34114-806d-4dba-a9ff-cc2c7b25a8fc.png)

**Comment by naelstrof** [comment]
Ah yeah, sorry. There's no way to really know what colliders are associated with what renderers and I just guess.

I shouldn't have used one of my helper functions. There's commands to render decals for specific renderers that you can use instead.
