### ISSUE TITLE
Can you do standard pipeline compatibility?

### ISSUE THREAD

**Issue by 2324268086** [naelstrof/SkinnedMeshDecals#5]
Can you do standard pipeline compatibility?

**Comment by naelstrof** [comment]
It already supports standard! Simply import the standard shaders unity package.

**Comment by naelstrof** [comment]
You can find it here: https://github.com/naelstrof/SkinnedMeshDecals/blob/master/Assets/Plugins/SkinnedMeshDecals/Shaders/StandardRP_Shaders.unitypackage

**Comment by 2324268086** [comment]
OK, but I found that it is based on shader, which is not what I want. It's too troublesome to modify skin shader

**Comment by naelstrof** [comment]
Unfortunately if you're unhappy with the included shaders, then you'll have to make your own.

It's very simple to make compatible shaders with Amplify Shader Editor, or just make a surface shader with your favorite text editor. All it needs is a texture reference with a specific name, and there's lots of ways you can use that texture for different kinds of effects.

**Comment by 2324268086** [comment]
Yes, maybe you can set two materials for the skin mesh and render the decal part separately, which can be compatible with any shader

**Comment by naelstrof** [comment]
> Yes, maybe you can set two materials for the skin mesh and render the decal part separately, which can be compatible with any shader

This is actually how it works! The decal projector is a platform agnostic frag shader. While the user is expected to create a shader that combines the resulting textures. Many samples were included to help, let me know if you need a specific kind of effect and I will do my best to show you how to get it to work!

**Comment by 2324268086** [comment]
It's very kind of you. Can you make a demo of the standard pipeline? As far as we know, the projected decals will not be distributed normally when the skin character plays the animation







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dalton ***@***.***&gt;; 
发送时间: 2021年10月4日(星期一) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [naelstrof/SkinnedMeshDecals] Can you do standard pipeline compatibility? (#5)





  
是的，也许你可以为皮肤网格设置两种材质并分别渲染贴花部分，可以与任何着色器兼容
  
这实际上是它的工作原理！贴花投影仪是一个与平台无关的碎片着色器。而用户需要创建一个结合结果纹理的着色器。包含许多示例以提供帮助，如果您需要特定类型的效果，请告诉我，我会尽力向您展示如何让它发挥作用！
 
—
您收到此消息是因为您创作了该线程。
直接回复此邮件，在 GitHub 上查看，或取消订阅。
使用 GitHub Mobile for iOS或Android随时随地分类通知。
