### ISSUE TITLE
URP not working?

### ISSUE THREAD

**Issue by renanvalentin** [naelstrof/SkinnedMeshDecals#9]
Hey @naelstrof thanks for creating this project and for sharing that in-depth detailed explanation. 

Would be possible to include a sample of it using URP? I tried to setup but `DecalColorMap`  is rendered as black and i'm not sure if this is due to bad settings. 

This is the plane material
![plane_material](https://user-images.githubusercontent.com/2846918/159132372-6c2a38ad-a9b8-41a5-ad48-601f0655e070.jpg)

The projector
![Screenshot 2022-03-19 144351](https://user-images.githubusercontent.com/2846918/159132389-ed2eb4c5-9c0b-434c-86d6-6892f1aab94d.jpg)

Tested using `DecalShooter.cs` provided in the sample folder

**Comment by naelstrof** [comment]
Yeah sorry the package has a lot of things that can go wrong. Make sure that your renderer has a collider on the same game object, and that its layer is one that decal shooter will hit.

Otherwise your setup looks good. I'm not sure what else would be wrong.

**Comment by Zennii** [comment]
I'm also having this problem, with the same settings above on a simple setup of 2 cubes, a large cube with a box collider and the Decalable/URP/Lit material and a small cube pointing its forward axis at it using the example DecalShooter script. The raycast is definitely hitting the cube, I have a debug log for when it does. No decal is painted on the big cube. I'd love to see an example too. I can provide an extremely simple project if my explanation of my setup is insufficient. Unity version 2020.3.30f1

**Comment by Zennii** [comment]
I've noticed when I select the projector material to view its properties, I get the following warning which may or may not be related:
```
Could not create a custom UI for the shader 'Naelstrof/DecalProjector'. The shader has the following: 'CustomEditor = ASEMaterialInspector'. Does the custom editor specified include its namespace? And does the class either derive from ShaderGUI or MaterialEditor?
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by naelstrof** [comment]
> I'm also having this problem, with the same settings above on a simple setup of 2 cubes, a large cube with a box collider and the Decalable/URP/Lit material and a small cube pointing its forward axis at it using the example DecalShooter script. The raycast is definitely hitting the cube, I have a debug log for when it does. No decal is painted on the big cube. I'd love to see an example too. I can provide an extremely simple project if my explanation of my setup is insufficient. Unity version 2020.3.30f1

Yeah sorry I'm not sure what's wrong. This utility is pretty easy to get the configuration wrong. If you want to add me on discord I'd love to help you via streaming: naelstrof#7705 
Otherwise yeah I need more information. A sample project would do.
